"""empty message

Revision ID: 026c6f303a85
Revises: 6ae781e773e7
Create Date: 2023-07-20 19:59:12.131327

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "026c6f303a85"
down_revision = "6ae781e773e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
