"""empty message

Revision ID: 6ae781e773e7
Revises: 6d7ae8ab0307
Create Date: 2023-07-20 17:28:09.349198

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6ae781e773e7"
down_revision = "6d7ae8ab0307"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
