"""empty message

Revision ID: 7b3e43e9ca48
Revises: 026c6f303a85
Create Date: 2023-07-20 20:00:57.336520

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7b3e43e9ca48"
down_revision = "026c6f303a85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
