"""empty message

Revision ID: 86dc1668c879
Revises: c19be1bb41be
Create Date: 2023-07-17 19:35:54.529544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dc1668c879'
down_revision = 'c19be1bb41be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('primary_keys', sa.Column('instance_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('primary_keys', 'instance_name')
    # ### end Alembic commands ###
