"""empty message

Revision ID: ac4dcfc6c73f
Revises: c9e19dbe65b3
Create Date: 2023-07-21 10:15:37.645246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4dcfc6c73f'
down_revision = 'c9e19dbe65b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
