"""empty message

Revision ID: c9e19dbe65b3
Revises: 7b3e43e9ca48
Create Date: 2023-07-21 08:52:52.772446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e19dbe65b3'
down_revision = '7b3e43e9ca48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
